### ISSUE TITLE
Save output : makes 64 files 

### ISSUE THREAD

**Issue by ArkhamInsanity** [lks-ai/ComfyUI-StableAudioSampler#10]
I am currently using this workflow

![Capture d’écran du 2024-06-09 18-07-37](https://github.com/lks-ai/ComfyUI-StableAudioSampler/assets/121449326/0f26a2fe-3b9a-4e17-b53c-30c8c1ee98f0)

When I queue it, the result is 64 files of 2.1kb each, giving no sound. No matter what value I give to the pre-conditionning nodes.
What should I do?
Thanks

**Comment by ArkhamInsanity** [comment]
Now I get two files with sound (identical it seems), so I guess it's working :D
![Capture d’écran du 2024-06-09 19-03-55](https://github.com/lks-ai/ComfyUI-StableAudioSampler/assets/121449326/d1ea1005-44ec-440c-85c4-18acf472f827)

**Comment by lks-ai** [comment]
I have changed the output formatting and this, so it should work with push I made last night. Let me know.

**Comment by ArkhamInsanity** [comment]
Yep, just tried and it's working, just one file saved per try. Thank you for the hard work, it's amazing !
