### ISSUE TITLE
Cannot access gated repo for (...) model_config.json

### ISSUE THREAD

**Issue by laurentVeliscek** [lks-ai/ComfyUI-StableAudioSampler#4]
I've installed the checkpoint and set an HF_token that is properly seen in my comfyUI venv, but I still get this error :

```
Error occurred when executing StableAudioSampler:

401 Client Error. (Request ID: Root=1-6661c64a-650c6885231247dc762904a8;cc528449-3958-4b38-81fc-a7064d4cf8b2)

Cannot access gated repo for url https://huggingface.co/stabilityai/stable-audio-open-1.0/resolve/main/model_config.json.

```
Any idea ?

**Comment by houdinii** [comment]
I believe you have to go to https://huggingface.co/stabilityai/stable-audio-open-1.0 and enter your information while logging into your Huggingface account. They have a set of terms and conditions to agree to before you can use their repo.

**Comment by lks-ai** [comment]
With the latest update, as long as you have model_config.json and model.safetensors in your audio checkpoints folder, you should be good to go.
