### ISSUE TITLE
progressbar

### ISSUE THREAD

**Issue by ioritree** [lks-ai/ComfyUI-StableAudioSampler#7]
```
Collecting progressbar (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1))
  Using cached http://mirrors.aliyun.com/pypi/packages/a3/a6/b8e451f6cff1c99b4747a2f7235aa904d2d49e8e1464e0b798272aa84358/progressbar-2.5.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\TEMP\pip-install-6d054hkt\progressbar_c40e21453ece474cafbfe32acd2111a5\setup.py", line 24, in <module>
          description=progressbar.__doc__.split('\n')[0],
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

+118cuda ,py310 ,windows11 
appear this error message after progressbar

**Comment by lks-ai** [comment]
This looks like a stable audio tools library issues.  Does this happen on install or on running the node?

**Comment by ioritree** [comment]
> This looks like a stable audio tools library issues. Does this happen on install or on running the node?

on install

**Comment by cherrerajobs** [comment]
I had to manually download progressbar and edit the line in the file that causes the error to get that to work. For me it was a line about version I believe.

**Comment by lks-ai** [comment]
What line did you have to edit @cherrerajobs ?

**Comment by cherrerajobs** [comment]
In the case shown above I would just edit line 24 of setup.py to:
`description='Progress Bar',`

https://pypi.org/project/progressbar/#files
![image](https://github.com/lks-ai/ComfyUI-StableAudioSampler/assets/8894763/3aee6277-5bc8-4488-8e24-b7a8541f466e)

**Comment by Reptiliano666** [comment]
Tengo el mismo problema con progressbar

**Comment by cherrerajobs** [comment]
@Reptiliano666 @ioritree @lks-ai 

Try/Intenta:
`/comfyui_folder/python_embeded/python.exe -m pip install progressbar2`

**Comment by lks-ai** [comment]
![image](https://github.com/lks-ai/ComfyUI-StableAudioSampler/assets/163685473/2ace505c-2ea1-4c49-b74b-21d4184f9139)
Espanyol: Estoy trabajando en un sistema de deteccion y sugerencias para problemas asi en todos nuestros packs de nodos.
English: I'm working on a system for detection and suggestions for these types of problems, should work across all our node packs.
